### ISSUE TITLE
Upcoming Wp-Adv-Quiz 1.0.1 To Do Task List

### ISSUE THREAD

**Issue by markusbegerow** [markusbegerow/Wp-Adv-Quiz#19]
Hello everyone,

in the upcoming update we will fix some parts in our quiz plugin:

Mandatory
 * [] html tags not parsed - https://github.com/markusbegerow/Wp-Adv-Quiz/issues/8 - thanks to @hmdadou
 * [] Translations - thanks to @gerard-merkator, @varuthai, @Vinnpinn, @Farisalqolop, @gvdb-ext
 * [] Modify button's colour - https://github.com/markusbegerow/Wp-Adv-Quiz/issues/1 - thanks to @hitestji

Stay tuned!

**Comment by SebJak** [comment]
Hi, when do you plan release version 1.0.1?

**Comment by markusbegerow** [comment]
Hi @SebJak ,
hey @all,

we plan to ship the new version on Easter, if everything works correctly.

For more transparency, we plan to put up a development plan next month.

Best regards
Markus

**Comment by markusbegerow** [comment]
Just tested the new shortcode version in Gutenberg.
Working like a charm:

![image](https://user-images.githubusercontent.com/44146279/229296741-77e648b7-cb75-4dc3-bc51-3f715968ac3b.png)

**Comment by markusbegerow** [comment]
https://user-images.githubusercontent.com/44146279/229302054-5906ab00-663f-4980-8a1f-ba5f99879aa9.png

**Comment by Tomer-Aharoni** [comment]
Nice!
Thank you for your good work :)
Is there any chance you'll get to release the new version even before Easter?

**Comment by markusbegerow** [comment]
Next step: Translation works, please contact me, if you wanna provide some translations
![image](https://user-images.githubusercontent.com/44146279/229350673-0d65da76-a9aa-441b-929a-7a29aee87fd2.png)

**Comment by markusbegerow** [comment]
Some improvements are comin'
![image](https://user-images.githubusercontent.com/44146279/229351982-6b6438d7-fceb-4077-a44b-8a41464294fb.png)

**Comment by markusbegerow** [comment]
What kind of objects do you wanna coloring?
![image](https://user-images.githubusercontent.com/44146279/229355352-410d501b-d7a3-45cd-b7b7-55f00a0600ff.png)

**Comment by markusbegerow** [comment]
Hey @Tomer-Aharoni,

thx for your qustion. I guess, we will do some unit tests this week. In the end of the upcoming week we can publish the new version.

**Comment by Tomer-Aharoni** [comment]
> 

Hi, I'm translating the current version of the plugin to my language on the wordpress.org site.
does it help? will the translation files sync when the new version will be uploaded to wordpress?
I will like to translate the new changes also to hebrew.

**Comment by markusbegerow** [comment]
Hello @Tomer-Aharoni, please translate your language after the rollout. We are beginning today with the unit-testing.

**Comment by markusbegerow** [comment]
Publish & Upload begins now
